### ISSUE TITLE
GUI Jobs fails for Rancher and Konvoy platforms

### ISSUE THREAD

**Issue by rohan2794** [mayadata-io/oep-e2e#692]
Some of the selenium based GUI jobs fails for Rancher and Konvoy .
Error 1: 
```
Installing collected packages: configparser, urllib3, selenium, more-itertools, pyparsing, six, packaging, py, wcwidth, attrs, zipp, importlib-metadata, pluggy, pytest, tblib, pytest-parallel, setuptools, pytest-rerunfailures, pytest-metadata, pytest-html, chardet, certifi, idna, requests
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.7/shutil.py", line 566, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/home/konvoy-oep/.local/lib/python3.7/site-packages/pytest-5.4.2.dist-info/RECORD.pip' -> '/home/konvoy-oep/.local/lib/python3.7/site-packages/pytest-5.4.2.dist-info/RECORD'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 335, in run
    prefix=options.prefix_path,
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 732, in install
    **kwargs
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 837, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 1039, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 526, in move_wheel_files
    shutil.move(temp_record, record)
  File "/usr/lib/python3.7/shutil.py", line 580, in move
    copy_function(src, real_dst)
  File "/usr/lib/python3.7/shutil.py", line 266, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/home/konvoy-oep/.local/lib/python3.7/site-packages/pytest-5.4.2.dist-info/RECORD.pip'
You are using pip version 8.1.1, however version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command. 
```

Error 2:

```
tests/dashboard_test.py::TestDashboard::test_verify_logs_dashboard PASSED
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/konvoy-oep/.local/lib/python3.7/site-packages/pytest_parallel/__init__.py", line 93, in run
INTERNALERROR>     run_test(self.session, item, None)
INTERNALERROR>   File "/home/konvoy-oep/.local/lib/python3.7/site-packages/pytest_parallel/__init__.py", line 54, in run_test
INTERNALERROR>     item.ihook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/home/konvoy-oep/.local/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/konvoy-oep/.local/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/konvoy-oep/.local/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/konvoy-oep/.local/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/konvoy-oep/.local/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/konvoy-oep/.local/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/konvoy-oep/.local/lib/python3.7/site-packages/_pytest/runner.py", line 85, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/home/konvoy-oep/.local/lib/python3.7/site-packages/_pytest/runner.py", line 94, in runtestprotocol
INTERNALERROR>     rep = call_and_report(item, "setup", log)
INTERNALERROR>   File "/home/konvoy-oep/.local/lib/python3.7/site-packages/_pytest/runner.py", line 188, in call_and_report
INTERNALERROR>     report = hook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR>   File "/home/konvoy-oep/.local/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/konvoy-oep/.local/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/konvoy-oep/.local/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/konvoy-oep/.local/lib/python3.7/site-packages/pluggy/callers.py", line 203, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "/home/konvoy-oep/oep-e2e-konvoy/gui-automation/conftest.py", line 73, in pytest_runtest_makereport
INTERNALERROR>     driver = item.funcargs['driver']
INTERNALERROR> KeyError: 'driver'
INTERNALERROR> 
INTERNALERROR> The above exception was the direct cause of the following exception:
INTERNALERROR> 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/konvoy-oep/.local/lib/python3.7/site-packages/_pytest/main.py", line 191, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/konvoy-oep/.local/lib/python3.7/site-packages/_pytest/main.py", line 247, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/konvoy-oep/.local/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/konvoy-oep/.local/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/konvoy-oep/.local/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/konvoy-oep/.local/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/konvoy-oep/.local/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/konvoy-oep/.local/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/konvoy-oep/.local/lib/python3.7/site-packages/pytest_parallel/__init__.py", line 323, in pytest_runtestloop
INTERNALERROR>     six.raise_from(exc, err[1])
INTERNALERROR>   File "<string>", line 3, in raise_from
INTERNALERROR> RuntimeError: pytest-parallel got 3 errors, raising the first from Thread-2.

================ 17 passed, 46 deselected in 314.50s (0:05:14) =================
```
Above two errors are quite random , every time it may happen in different jobs in a pipeline.

**Comment by AmitKumarDas** [comment]
@rohan2794 How is the program executed? Is the program executed inside a container?
Or is the program executed from the host OS directly?

**Comment by rohan2794** [comment]
Once the job failed with above error , if we re run the job it will pass without any error.

**Comment by rohan2794** [comment]
@AmitKumarDas Tests are executed from the host OS directly.

**Comment by rohan2794** [comment]
We are running tests in parallel using `pytest-parallel` plugin.
In AWS, it's working as expected.

**Comment by rohan2794** [comment]
```
platform linux -- Python 3.7.7, pytest-5.4.2, py-1.8.2, pluggy-0.13.1 -- /usr/bin/python3.7
cachedir: .pytest_cache
metadata: {'Python': '3.7.7', 'Platform': 'Linux-4.15.0-99-generic-x86_64-with-Ubuntu-16.04-xenial', 'Packages': {'pytest': '5.4.2', 'py': '1.8.2', 'pluggy': '0.13.1'}, 'Plugins': {'forked': '1.1.3', 'xdist': '1.32.0', 'allure-pytest': '2.8.10', 'rerunfailures': '8.0', 'html': '2.1.0', 'parallel': '0.1.0', 'metadata': '1.9.0'}}
rootdir: /home/konvoy-oep/oep-e2e-konvoy/gui-automation, inifile: pytest.ini
plugins: forked-1.1.3, xdist-1.32.0, allure-pytest-2.8.10, rerunfailures-8.0, html-2.1.0, parallel-0.1.0, metadata-1.9.0
```

**Comment by rohan2794** [comment]
Above Error resolved be setting up separate Selenium Grid in Lab network for Rancher and Konvoy . Removed all dependency on grid deployed on AWS for both platforms.
